### ISSUE TITLE
AWS Fundamentals 11번 랩

### ISSUE THREAD

**Issue by alpakalee** [kwanghoon/cyberbit#2]
랩 로딩 시간을 전부 기다려도 로딩이 되지않습니다.
![스크린샷 2024-06-10 121049](https://github.com/kwanghoon/cyberbit/assets/105830543/a3b4f968-33f1-4262-922c-0a1d446d60ee)

**Comment by kwanghoon** [comment]
@alpakalee  It was the internal problem of Cyberbit. Now it was resolved.
